FROM node:20-alpine

WORKDIR /app

# Install dependencies needed for node-gyp or other native builds if any
RUN apk add --no-cache libc6-compat python3 make g++

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "run", "dev"]
